/* ************************************************************ */
/* DO NOT EDIT THIS FILE! IT IS GENERATED BY QMAKE PROJECT FILE */
/*                 EDIT version.txt FILE INSTEAD                */
/*              Requires Build > Run qmake command              */
/* ************************************************************ */
#pragma once
#define REDINAV_VERSION "1.0.24"
